FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/bidding ./cmd/bidding

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/bidding /bin/bidding
EXPOSE 8081
ENTRYPOINT ["/bin/bidding"]
