FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/consumer ./cmd/consumer

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/consumer /bin/consumer
ENTRYPOINT ["/bin/consumer"]
