global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bidding'
    static_configs:
      - targets: ['bidding:8081']
    metrics_path: /metrics

  - job_name: 'campaign'
    static_configs:
      - targets: ['campaign:8082']
    metrics_path: /metrics

  - job_name: 'krakend'
    static_configs:
      - targets: ['gateway:9091']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
